In [245]:
import numpy as np
import pandas as pd

In [246]:
import os
os.getcwd()
os.chdir('/Users/ahsan/Documents/Coursera/machine-learning-ex/ex1')
os.getcwd()

'/Users/ahsan/Documents/Coursera/machine-learning-ex/ex1'

In [247]:
data1 = pd.read_csv('ex1data1.txt')

In [248]:
data1.columns = ['Size', 'Price']

In [249]:
data2 = pd.read_csv('ex1data2.txt')
data2.columns = ['Size', 'Bedrooms', 'Price']

In [250]:
data1.head()

Size    Price
0  5.5277   9.1302
1  8.5186  13.6620
2  7.0032  11.8540
3  5.8598   6.8233
4  8.3829  11.8860

In [251]:
X = np.ones(shape=(len(data1), 2))
X[:,1] = data1['Size']
y = data1.values
y = y[:,1]
print(X.shape)
print(y.shape)

(96, 2)
(96,)


In [252]:
theta = np.array([0,0])
theta
theta.shape

(2,)

In [253]:
np.sum(np.square( np.dot(X,theta) - y ) )

5912.6319082264

## Computing Cost Function

In [254]:
m = len(data1)

#Implementing the Cost Function
def computeCost(X,y,theta):
    J = (1/(2*m)) *  np.sum(np.square( np.dot(X,theta) - y ) )
    return J

In [255]:
computeCost(X,y,theta)

30.79495785534583

## Gradient Descent Function

In [256]:
theta -  0.00001 *(np.dot(np.matrix.transpose(X),(np.dot(X,theta) - y)) / m )

array([5.71670937e-05, 6.48896828e-04])

In [272]:
def GradientDescent(X,y,theta,alpha):
    num_iter = 100000
    for i in range(num_iter):
        theta = theta -  alpha *(np.dot(np.matrix.transpose(X),(np.dot(X,theta) - y)) / m )
        if (i % 10000 == 0):
            print('Cost at Iteration# ' + str(i) + " is "+str(computeCost(X,y,theta)))
    return theta

## Computing Gradient Descent with One Variable

In [273]:
alpha = 0.0009
GradientDescent(X,y,theta,alpha)

Cost at Iteration# 0 is 0.4991621789282699
Cost at Iteration# 10000 is 0.1328749574184971
Cost at Iteration# 20000 is 0.1328396234781045
Cost at Iteration# 30000 is 0.13283961041774517
Cost at Iteration# 40000 is 0.13283961041291772
Cost at Iteration# 50000 is 0.13283961041291595
Cost at Iteration# 60000 is 0.13283961041291592
Cost at Iteration# 70000 is 0.13283961041291592
Cost at Iteration# 80000 is 0.13283961041291595
Cost at Iteration# 90000 is 0.13283961041291592


array([ 8.32763206e-17,  8.83934632e-01, -4.99195578e-02])

In [281]:
theta = np.array([0,0,0])
m = len(data2)
X = np.ones(shape=(len(data2), 3))
X[:,1] = data2['Size']
X[:,2] = data2['Bedrooms']
y = data2.values
y = y[:,2]




In [ ]:
X[:,1] = ( X[:,1] -  np.mean(X[:,1]) ) / (np.std(X[:,1]))
X[:,2] = ( X[:,2] -  np.mean(X[:,2]) ) / (np.std(X[:,2]))
y = ( y - np.mean(y) ) / np.std(y)



## Gradient Descent with two Variables

In [275]:
alpha = 0.009
GradientDescent(X,y,theta,alpha)

Cost at Iteration# 0 is 0.49167135613416413
Cost at Iteration# 10000 is 0.13283961041291595
Cost at Iteration# 20000 is 0.13283961041291595
Cost at Iteration# 30000 is 0.13283961041291595
Cost at Iteration# 40000 is 0.13283961041291595
Cost at Iteration# 50000 is 0.13283961041291595
Cost at Iteration# 60000 is 0.13283961041291595
Cost at Iteration# 70000 is 0.13283961041291595
Cost at Iteration# 80000 is 0.13283961041291595
Cost at Iteration# 90000 is 0.13283961041291595


array([ 5.55805402e-17,  8.83934632e-01, -4.99195578e-02])

## Normal Equation Implementation

In [277]:
def NormalEquation(X,y,theta):
    theta = np.dot( np.linalg.inv(np.dot(np.matrix.transpose(X),X))  , np.dot(np.matrix.transpose(X),y) )
    return theta